# config.yaml
server:
  port: "9090"
  host: "0.0.0.0"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "todo_db"
  sslmode: "disable"

jwt:
  secret: "your-secret-key"
  expiration: "24h"